name: Python formatting

on: [push, pull_request]

jobs:
  lint:
    name: Run black
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: psf/black@8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b # stable
        with:
          src: "./unitary"
