name: Pylint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Pylint check
        # TODO: #210 - convert to hard check when lint is picked up
        run: |
          dev_tools/pylint || (
            echo "pylint check failed.  The error is temporarily ignored."
            echo "See https://github.com/quantumlib/unitary/issues/210"
          )
