name: Pylint

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  pylint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Set up problem matcher for Pylint output
        run: echo '::add-matcher::.github/problem-matchers/pylint.json'
      - name: Pylint check
        run: dev_tools/pylint
