name: Pylint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Pylint check
        run: dev_tools/pylint
